registration:
  post:
    tags:
      - User
    summary: Register a new user
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/UserRegistrationRequest'
    responses:
      200:
        description: Successful registration
        content: { }
      409:
        description: Conflict (email already registered)
        content:
          application/json:
            schema:
              $ref: 'openapi.yaml#/components/schemas/ErrorResponse'
            example:
              status: 409
              message: "Password does not match. by email: {email}"
              details: ""
              timestamp: "2023-04-20T12:00:00Z"


#shema

UserRegistrationRequest:
  type: object
  properties:
    email:
      type: string
      format: email
    password:
      type: string
      minLength: 6
    recoverPassword:
      type: string
      minLength: 6