openapi: "3.0.3"


info:
  title: "Test work Exchange rate"
  description: "Average Exchange rate "
  contact:
    name: "Exchange rate"
    url: "http://localhost:8080"
    email: "4pnav21@gmail.com"
  version: "1.0.0"


servers:
  - url: "http://localhost:8080"
    description: "Local server"

paths:

  # ExchangeRate

  /exchanges:
    $ref: "openapi-exchange-rate.yaml#/exchanges"
  /exchanges/periods:
    $ref: "openapi-exchange-rate.yaml#/exchanges-periods"


tags:

  - name: ExchangeRate
    description: Exchange rate

