exchanges:
  get:
    tags:
      - ExchangeRate
    summary: Get average exchange rates for a given period
    responses:
      200:
        description: A list of average exchange rates
        content:
          application/json:
            schema:
              $ref: '#/AverageExchangeRateDto'

exchanges-periods:
  get:
    tags:
      - ExchangeRate
    summary: Get average exchange rates for a given period
    parameters:
      - in: query
        name: from
        schema:
          type: string
          format: date-time
        required: true
        description: Start date and time of the period
        example: "2023-01-01T00:00:00Z"
      - in: query
        name: to
        schema:
          type: string
          format: date-time
        required: true
        description: End date and time of the period
        example: "2023-01-31T23:59:59Z"
    responses:
      200:
        description: A list of average exchange rates
        content:
          application/json:
            schema:
              $ref: '#/AverageExchangeRateDto'


#shema

AverageExchangeRateDto:
  type: object
  properties:
    content:
      type: array
      items:
        type: object
        properties:
          currency:
            type: string
          averageRateBuy:
            type: number
            format: double
          averageRateSell:
            type: number
            format: double