create table exchange_rates
(
    id         bigint generated by default as identity
        primary key,
    exchanger  varchar(255)   not null,
    currency   varchar(255)   not null,
    rate_buy   numeric(19, 4) not null,
    rate_sell  numeric(19, 4),
    date       timestamp      not null,
    created_at timestamp      not null
);